### ISSUE TITLE
PA2

### ISSUE THREAD

**Issue by vkuzn** [kvdovkin/DP#1]
1. В папке nginx должна находится только папка conf с одним файлом nginx.conf
Никакие бинарники в репозитории лежать не должны

2. start.cmd не запускает приложение. Мои действия: выкачиваю репозиторий в новую папку и запускаю start.cmd. Выполняйте у себя эти действия перед тем как сдавать работы.

**Comment by kvdovkin** [comment]
Исправил, перепроверьте
