### ISSUE TITLE
PA7

### ISSUE THREAD

**Issue by vkuzn** [kvdovkin/DP#2]
Проект Chain должен лежать в корне репозитория. У вас вложенный путь Chain/Chain.

**Comment by kvdovkin** [comment]
Исправил

**Comment by vkuzn** [comment]
1. Приложение не работает. Имейте ввиду, что поцессы стартуют в разное время и удалённый сокет может ещё не быть готовым для установления соединения. В BeginConnect обычно передается callback-функция, в которой проверяется результат выполнения, но рекомендую вместо BeginConnect пользоваться методом Socket.ConnectAsync:
https://github.com/kvdovkin/DP/blob/7412c1ed03973252ecc27134cbaac9dbae45a4e3/Chain/Program.cs#L87
2. Почитайте про чистые функции (pure functions) и побочные эффекты (side effects). Тут явно можно обойтись без побочного эффекта:
https://github.com/kvdovkin/DP/blob/7412c1ed03973252ecc27134cbaac9dbae45a4e3/Chain/Program.cs#L56
3. Приложение будет работать неверно: размера буфера в 4 байт не хватит для передачи числа 50000 в строковом представлении. Исправьте и аргументируйте пожалуйста ваше решение передавать числа в виде строки.

**Comment by kvdovkin** [comment]
Исправил

**Comment by vkuzn** [comment]
Размера буфера в 4 байт не хватит для передачи 5-значного числа в строковом виде, например "50000". Как результат - приложение работает неверно.
Запускаются 3 процесса с входными данными 187650, 70000, 3 соответственно. Ожидаем вывод 187650 у всех процессов, но выводится мусор:
![image](https://user-images.githubusercontent.com/25608388/122533330-1ab1dd00-d02a-11eb-8e23-f99a720bed62.png)

Если передаётся число в виде строки, то обесьпечте необходимый размер буфера для чтения. Но лучше будет конвертировать число напрямую в массив byte[], в этом случае размера буфера в 4 байт будет достаточно.

**Comment by kvdovkin** [comment]
Исправил
